skillMetadata:
  sections:
    - name: Internal Settings
      fields:
        - name: sock_path
          type: text
          label: MPV Socket path
          value: /tmp/mpv
    - name: Playback Settings
      fields:
        - name: volume
          type: number
          label: Playback Volume Scaler
          value: "1.0"